<a href="https://colab.research.google.com/github/jadercaro/Prediccion-de-desercion-universitaria/blob/main/1_Preprocesamiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cargamos la base de datos y Librerias

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import os
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings('ignore')
!git clone https://github.com/jadercaro/Prediccion-de-desercion-universitaria
os.chdir('/content/Prediccion-de-desercion-universitaria/dataset')

Cloning into 'Prediccion-de-desercion-universitaria'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 86 (delta 34), reused 11 (delta 4), pack-reused 0
Receiving objects: 100% (86/86), 3.22 MiB | 4.80 MiB/s, done.
Resolving deltas: 100% (34/34), done.

In [2]:
df = pd.read_csv('datos1.csv')

# Transformación de variables

## Codificación de las variables categóricas
Usaremos el método de codificación One Hot Encoding para las variables catégoricas que tengan más de dos catégorias

In [3]:
variables_codificar = ['Marital status', 'Application mode', 'Application order', 'Course',
                       'Previous qualification','Nacionality','''Mother's qualification''', '''Father's qualification''',
                      '''Mother's occupation''', '''Father's occupation''']

encoder = OneHotEncoder(sparse=False)

# Ajustar y transformar las columnas categóricas
encoded_data = encoder.fit_transform(df[variables_codificar])


# Crear un DataFrame con las columnas codificadas
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(variables_codificar))

#Convertimos las variables a tipo bool
encoded_df=encoded_df.astype(bool)

# Concatenar el DataFrame original con el DataFrame codificado
final_df = pd.concat([df, encoded_df], axis=1)

#Eliminamos las columnas ya co
final_df = final_df.drop(columns=variables_codificar)

## Convertimos las variables Booleanas a tipo Bool

In [4]:
columnas_bool = ['Daytime/evening attendance\t', 'Displaced', 'Educational special needs', 'Debtor',
                 'Tuition fees up to date', 'Gender','Scholarship holder', 'International', 'Target']
final_df[columnas_bool] = final_df[columnas_bool].astype(bool)

## Escalamientos de variables númericas
Elimina la media, media = 0, y varianza = 1, se hace esto para obtener mejor rendimiento en los modelos, se debe tener cuidado en la interpretación de los resultados obtenidos

In [5]:
var_estandarizar = final_df.select_dtypes(exclude=bool).columns

# Crea un objeto StandardScaler
scaler = StandardScaler()

# Ajusta el scaler a las columnas seleccionadas y luego transforma las columnas
columnas_escaladas = scaler.fit_transform(final_df[var_estandarizar])

# Reemplaza las columnas originales con las columnas escaladas
final_df[var_estandarizar] = columnas_escaladas

In [6]:
final_df

,Daytime/evening attendance\t,Previous qualification (grade),Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,...,Father's occupation_172,Father's occupation_174,Father's occupation_175,Father's occupation_181,Father's occupation_182,Father's occupation_183,Father's occupation_192,Father's occupation_193,Father's occupation_194,Father's occupation_195
0,True,-0.804841,0.022229,True,False,False,True,True,False,-0.430363,...,False,False,False,False,False,False,False,False,False,False
1,True,2.076819,1.071926,True,False,False,False,True,False,-0.562168,...,False,False,False,False,False,False,False,False,False,False
2,True,-0.804841,-0.150419,True,False,False,False,True,False,-0.562168,...,False,False,False,False,False,False,False,False,False,False
3,True,-0.804841,-0.509526,True,False,False,True,False,False,-0.430363,...,False,False,False,False,False,False,False,False,False,False
4,False,-2.473171,1.002867,False,False,False,True,False,False,2.864765,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,True,-0.577342,-0.329972,False,False,False,True,True,False,-0.562168,...,False,False,False,False,False,False,False,False,False,False
4420,True,-0.956508,-0.550961,True,False,True,False,False,False,-0.693973,...,False,False,False,False,False,False,False,False,False,False
4421,True,1.621820,1.555339,True,False,False,True,False,True,0.887688,...,False,False,False,False,False,False,False,False,False,False
4422,True,3.593483,1.852293,True,False,False,True,False,True,-0.430363,...,False,False,False,False,False,False,False,False,False,False
4423,True,1.470154,1.727987,True,False,False,True,False,False,-0.166753,...,False,False,False,False,False,False,False,False,False,False

In [7]:
final_df.to_csv('datos_modelo.csv', index=False)